version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback 
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - setup_remote_docker
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name:  "Build Docker and push" 
          command: |
            cp Dockerfile.production Dockerfile
            docker build . -t smjtheoff/devops-test-express:lastst
            docker build . -t smjtheoff/devops-test-express:${CIRCLE_SHA1}
            docker push smjtheoff/devops-test-express:lastst
            docker push smjtheoff/devops-test-express:${CIRCLE_SHA1}
  deploy:
    docker:
       - image: circleci/node:8.11.1-stretch
    steps:
      - run :
            name : "Deployment at rancher"
            command : |
              docker run --rm -it \
                -e CATTLE_ACCESS_KEY="$CATTLE_ACCESS_KEY" \
                -e CATTLE_SECRET_KEY="$CATTLE_SECRET_KEY" \
                -e CATTLE_URL="$CATTLE_URL" \
                etlweather/gaucho upgrade $RANCHER_SERVICE \
                --imageUuid 'docker:smjtheoff/devops-test-express:${CIRCLE_SHA1}' \
                --batch_size 5 --start_first \
                --auto_complete --timeout=600
      - run: echo Done
workflows:
  version: 2
  test_deplpy_w_workflow:
      jobs:
        - build
        - deploy:
            # type: approval
            requires:
              - build
